example/config/routes.rb
Example::Application.routes.draw do
  resources :parts

  resources :assemblies

end

example/app/models/assembly.rb
class Assembly < ActiveRecord::Base
end

example/app/models/part.rb
class Part < ActiveRecord::Base
end

example/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

example/app/controllers/assemblies_controller.rb
class AssembliesController < ApplicationController
  # GET /assemblies
  # GET /assemblies.json
  def index
    @assemblies = Assembly.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assemblies }
    end
  end

  # GET /assemblies/1
  # GET /assemblies/1.json
  def show
    @assembly = Assembly.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @assembly }
    end
  end

  # GET /assemblies/new
  # GET /assemblies/new.json
  def new
    @assembly = Assembly.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @assembly }
    end
  end

  # GET /assemblies/1/edit
  def edit
    @assembly = Assembly.find(params[:id])
  end

  # POST /assemblies
  # POST /assemblies.json
  def create
    @assembly = Assembly.new(params[:assembly])

    respond_to do |format|
      if @assembly.save
        format.html { redirect_to @assembly, notice: 'Assembly was successfully created.' }
        format.json { render json: @assembly, status: :created, location: @assembly }
      else
        format.html { render action: "new" }
        format.json { render json: @assembly.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assemblies/1
  # PUT /assemblies/1.json
  def update
    @assembly = Assembly.find(params[:id])

    respond_to do |format|
      if @assembly.update_attributes(params[:assembly])
        format.html { redirect_to @assembly, notice: 'Assembly was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @assembly.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assemblies/1
  # DELETE /assemblies/1.json
  def destroy
    @assembly = Assembly.find(params[:id])
    @assembly.destroy

    respond_to do |format|
      format.html { redirect_to assemblies_url }
      format.json { head :ok }
    end
  end
end

example/app/controllers/parts_controller.rb
class PartsController < ApplicationController
  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parts }
    end
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
    @part = Part.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @part }
    end
  end

  # GET /parts/new
  # GET /parts/new.json
  def new
    @part = Part.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @part }
    end
  end

  # GET /parts/1/edit
  def edit
    @part = Part.find(params[:id])
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(params[:part])

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render json: @part, status: :created, location: @part }
      else
        format.html { render action: "new" }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parts/1
  # PUT /parts/1.json
  def update
    @part = Part.find(params[:id])

    respond_to do |format|
      if @part.update_attributes(params[:part])
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part = Part.find(params[:id])
    @part.destroy

    respond_to do |format|
      format.html { redirect_to parts_url }
      format.json { head :ok }
    end
  end
end

example/app/helpers/application_helper.rb
module ApplicationHelper
end

example/app/helpers/assemblies_helper.rb
module AssembliesHelper
end

example/app/helpers/parts_helper.rb
module PartsHelper
end

example/app/views/assemblies/_form.html.erb
<%= form_for(@assembly) do |f| %>
  <% if @assembly.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assembly.errors.count, "error") %> prohibited this assembly from being saved:</h2>

      <ul>
      <% @assembly.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

example/app/views/assemblies/edit.html.erb
<h1>Editing assembly</h1>

<%= render 'form' %>

<%= link_to 'Show', @assembly %> |
<%= link_to 'Back', assemblies_path %>

example/app/views/assemblies/index.html.erb
<h1>Listing assemblies</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assemblies.each do |assembly| %>
  <tr>
    <td><%= assembly.name %></td>
    <td><%= link_to 'Show', assembly %></td>
    <td><%= link_to 'Edit', edit_assembly_path(assembly) %></td>
    <td><%= link_to 'Destroy', assembly, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Assembly', new_assembly_path %>

example/app/views/assemblies/new.html.erb
<h1>New assembly</h1>

<%= render 'form' %>

<%= link_to 'Back', assemblies_path %>

example/app/views/assemblies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @assembly.name %>
</p>


<%= link_to 'Edit', edit_assembly_path(@assembly) %> |
<%= link_to 'Back', assemblies_path %>

example/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Example</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

example/app/views/parts/_form.html.erb
<%= form_for(@part) do |f| %>
  <% if @part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
      <% @part.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

example/app/views/parts/edit.html.erb
<h1>Editing part</h1>

<%= render 'form' %>

<%= link_to 'Show', @part %> |
<%= link_to 'Back', parts_path %>

example/app/views/parts/index.html.erb
<h1>Listing parts</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parts.each do |part| %>
  <tr>
    <td><%= part.name %></td>
    <td><%= link_to 'Show', part %></td>
    <td><%= link_to 'Edit', edit_part_path(part) %></td>
    <td><%= link_to 'Destroy', part, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Part', new_part_path %>

example/app/views/parts/new.html.erb
<h1>New part</h1>

<%= render 'form' %>

<%= link_to 'Back', parts_path %>

example/app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @part.name %>
</p>


<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>